# site.yml
---
- name: Deploy Lab Infrastructure
  hosts: all
  become: false  # Change this from true to false

  pre_tasks:
    - name: Update package cache
      ansible.builtin.package:
        update_cache: true
      become: true  # Add this line to use privilege escalation only for this task
      changed_when: false
      when: ansible_pkg_mgr in ['dnf', 'yum']

    - name: Stop and disable original binary services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - named
        - dhcpd
        - nfs-server
      failed_when: false
      become: true  # Add this line

  roles:
    - role: common
      tags: ['common']

    - role: dns
      tags: ['dns']
      when: "'dns_servers' in group_names"

    - role: dhcp
      tags: ['dhcp']
      when: "'dhcp_servers' in group_names"

    - role: nfs
      tags: ['nfs']
      when: "'nfs_servers' in group_names"

  post_tasks:
    - name: Verify services
      tags: ['verify']
      block:
        - name: Test DNS resolution
          ansible.builtin.command: dig @{{ dns_server_ip }} infra.lab.com
          register: dns_test
          changed_when: false
          failed_when:
            - dns_test.rc != 0
            - "'Connection refused' not in dns_test.stderr"
          when: "'dns_servers' in group_names"

        - name: Test DHCP service
          ansible.builtin.command: nmap -sU -p 67 {{ dhcp_server_ip }}
          register: dhcp_test
          changed_when: false
          failed_when:
            - dhcp_test.rc != 0
            - "'Connection refused' not in dhcp_test.stderr"
          when: "'dhcp_servers' in group_names"

        - name: Test NFS exports
          ansible.builtin.command: showmount -e {{ nfs_server_ip }}
          register: nfs_test
          changed_when: false
          failed_when:
            - nfs_test.rc != 0
            - "'Connection refused' not in nfs_test.stderr"
          when: "'nfs_servers' in group_names"

        - name: Enable podman socket for systemd
          ansible.builtin.systemd:
            name: podman.socket
            enabled: true
            state: started
          become: true

        - name: Create podman configuration directory
          ansible.builtin.file:
            path: ~/.config/containers
            state: directory
            mode: '0755'
          become: false

        - name: Configure podman storage
          ansible.builtin.copy:
            dest: ~/.config/containers/storage.conf
            content: |
              [storage]
              driver = "overlay"
              runroot = "/run/user/{{ ansible_user_uid }}"
              graphroot = "$HOME/.local/share/containers/storage"
            mode: '0644'
          become: false

        - name: Create podman run directory
          ansible.builtin.file:
            path: "/run/user/{{ ansible_user_uid }}"
            state: directory
            mode: '0700'
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_id }}"
          become: true
