# site.yml
---
- name: Deploy Lab Infrastructure
  hosts: all
  become: true

  pre_tasks:
    - name: Update package cache
      ansible.builtin.package:
        update_cache: true
      changed_when: false
      when: ansible_pkg_mgr in ['dnf', 'yum']

  roles:
    - role: common
      tags: ['common']

    - role: dns
      tags: ['dns']
      when: "'dns_servers' in group_names"

    - role: dhcp
      tags: ['dhcp']
      when: "'dhcp_servers' in group_names"

    - role: nfs
      tags: ['nfs']
      when: "'nfs_servers' in group_names"

  post_tasks:
    - name: Verify services
      block:
        - name: Test DNS resolution
          ansible.builtin.command: dig @{{ dns_server_ip }} infra.lab.com
          register: dns_test
          changed_when: false
          failed_when:
            - dns_test.rc != 0
            - "'Connection refused' not in dns_test.stderr"
          when: "'dns_servers' in group_names"

        - name: Test DHCP service
          ansible.builtin.command: nmap -sU -p 67 {{ dhcp_server_ip }}
          register: dhcp_test
          changed_when: false
          failed_when:
            - dhcp_test.rc != 0
            - "'Connection refused' not in dhcp_test.stderr"
          when: "'dhcp_servers' in group_names"

        - name: Test NFS exports
          ansible.builtin.command: showmount -e {{ nfs_server_ip }}
          register: nfs_test
          changed_when: false
          failed_when:
            - nfs_test.rc != 0
            - "'Connection refused' not in nfs_test.stderr"
          when: "'nfs_servers' in group_names"
      tags: ['verify']
