# uninstall.yml
---
- name: Uninstall Lab Infrastructure
  hosts: all
  become: true

  tasks:
    - name: Stop and disable systemd services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
        scope: user
      loop:
        - dns-server
        - dhcp-server
      when: "'dns_servers' in group_names or 'dhcp_servers' in group_names"
      register: service_stop
      failed_when:
        - service_stop.failed is defined
        - service_stop.failed
        - '"Could not find the requested service" not in service_stop.msg'

    - name: Stop and disable NFS server
      ansible.builtin.systemd:
        name: nfs-server
        state: stopped
        enabled: false
      when: "'nfs_servers' in group_names"
      register: nfs_stop
      failed_when:
        - nfs_stop.failed is defined
        - nfs_stop.failed
        - '"Could not find the requested service" not in nfs_stop.msg'

    - name: Remove containers
      containers.podman.podman_container:
        name: "{{ item }}"
        state: absent
      loop:
        - dns-server
        - dhcp-server
      when: "'dns_servers' in group_names or 'dhcp_servers' in group_names"
      register: container_remove
      failed_when:
        - container_remove.failed is defined
        - container_remove.failed
        - '"not found" not in container_remove.msg'

    - name: Remove container images
      containers.podman.podman_image:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ container_registry }}/dns-server"
        - "{{ container_registry }}/dhcp-server"
      when: "'dns_servers' in group_names or 'dhcp_servers' in group_names"
      register: image_remove
      failed_when:
        - image_remove.failed is defined
        - image_remove.failed
        - '"not found" not in image_remove.msg'

    - name: Remove systemd service files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ systemd_user_dir }}/dns-server.service"
        - "{{ systemd_user_dir }}/dhcp-server.service"
      when: "'dns_servers' in group_names or 'dhcp_servers' in group_names"

    - name: Remove NFS exports
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ nfs_exports }}"
      when: "'nfs_servers' in group_names"

    - name: Remove lab-infra directory
      ansible.builtin.file:
        path: "~/lab-infra"
        state: absent

    - name: Remove firewall rules
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: disabled
      loop:
        - dns
        - dhcp
        - nfs
        - rpc-bind
        - mountd
      notify: "Reload firewall"

  handlers:
    - name: Reload firewall
      ansible.builtin.command: firewall-cmd --reload
      changed_when: true
