# inventory/hosts.yml
---
all:
  hosts:
    192.168.10.2:
      ansible_connection: ssh
      ansible_user: devcloud
  children:
    dns_servers:
      hosts:
        192.168.10.2:
    dhcp_servers:
      hosts:
        192.168.10.2:
    nfs_servers:
      hosts:
        192.168.10.2:
