# roles/nfs/handlers/main.yml
---
- name: Restart NFS service
  ansible.builtin.systemd:
    name: nfs-server
    state: restarted

- name: Reload firewall
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
