# roles/dns/handlers/main.yml
---
- name: Reload firewall configuration
  ansible.builtin.command: firewall-cmd --reload
  become: true
  changed_when: true
  listen: "Reload firewall"

- name: Restart DNS service
  ansible.builtin.systemd:
    name: dns-server
    state: restarted
    scope: user
  listen: "Restart DNS"

- name: Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  listen: "Reload systemd"
