# roles/nfs/tasks/main.yml
---
- name: Create NFS export directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    owner: "nobody"
    group: "nobody"
  loop: "{{ nfs_exports }}"

- name: Configure NFS exports
  ansible.builtin.template:
    src: "exports.j2"
    dest: "/etc/exports"
    mode: '0644'
  notify: "Restart NFS service"

- name: Enable and start NFS server
  ansible.builtin.systemd:
    name: nfs-server
    state: started
    enabled: true

- name: Configure firewall for NFS
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - nfs
    - rpc-bind
    - mountd
  notify: "Reload firewall"
