---
# roles/dns/tasks/main.yml

- name: Create DNS directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "~/lab-infra/dns/config"
    - "~/lab-infra/dns/data"
    - "~/lab-infra/dns/src"

- name: Create DNS validation directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: true
  loop:
    - "/etc/bind"
    - "/var/lib/bind"
    - "/var/named/data"
    - "/var/named/dynamic"

- name: Set DNS directory permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  become: true
  loop:
    - "/etc/bind"
    - "/var/lib/bind"

- name: Copy DNS Dockerfile
  template:
    src: "Dockerfile.j2"
    dest: "~/lab-infra/dns/src/Dockerfile"
    mode: '0644'

- name: Generate DNS configuration
  template:
    src: "{{ item.src }}"
    dest: "~/lab-infra/dns/config/{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'named.conf.j2', dest: 'named.conf' }
    - { src: 'db.lab.com.j2', dest: 'db.lab.com' }
    - { src: 'db.reverse.j2', dest: 'db.10.168.192' }

- name: Validate DNS configuration
  command: "named-checkconf ~/lab-infra/dns/config/named.conf"
  changed_when: false
  register: named_conf_check

- name: Validate forward zone
  command: "named-checkzone {{ base_domain }} ~/lab-infra/dns/config/db.lab.com"
  changed_when: false
  register: forward_zone_check

- name: Validate reverse zone
  command: "named-checkzone 10.168.192.in-addr.arpa ~/lab-infra/dns/config/db.10.168.192"
  changed_when: false
  register: reverse_zone_check

- name: Build DNS container
  containers.podman.podman_image:
    name: "{{ container_registry }}/dns-server"
    path: "~/lab-infra/dns/src"
    force: yes
  register: dns_image_build

- name: Stop existing DNS container
  containers.podman.podman_container:
    name: dns-server
    state: absent
  ignore_errors: true

- name: Create DNS systemd service directory
  file:
    path: "{{ systemd_user_dir }}"
    state: directory
    mode: '0755'

- name: Template DNS systemd service
  template:
    src: "dns-server.service.j2"
    dest: "{{ systemd_user_dir }}/dns-server.service"
    mode: '0644'
  register: dns_service_file

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
    scope: user
  when: dns_service_file.changed

- name: Enable and start DNS service
  systemd:
    name: dns-server
    state: started
    enabled: yes
    scope: user

- name: Configure firewall for DNS
  firewalld:
    service: dns
    permanent: yes
    state: enabled
  become: true
  notify: reload firewall

- name: Wait for DNS service to be ready
  wait_for:
    host: "{{ dns_server_ip }}"
    port: 53
    timeout: 30

- name: Verify DNS resolution
  command: "dig @{{ dns_server_ip }} infra.{{ base_domain }}"
  changed_when: false
  register: dns_test
  until: dns_test.rc == 0
  retries: 3
  delay: 5
