# roles/selinux/handlers/main.yml
---
- name: Restart infrastructure services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - named
    - dhcpd
    - nfs-server
  become: true
