# .github/workflows/ansible-lint.yml
---
name: Ansible Lint

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - 'roles/**'
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - 'roles/**'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core>=2.12.0 ansible-lint>=6.0.0

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install -r collections/requirements.yml

      - name: Run ansible-lint
        run: |
          ansible-lint -p --force-color
        env:
          ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections
